# Generated by Django 4.2.7 on 2023-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth1",
            name="email",
            field=models.EmailField(
                db_comment="Poll question", max_length=254, unique=True
            ),
        ),
    ]
