# Generated by Django 4.2.7 on 2023-11-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_auth1_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth1",
            name="final_otp",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auth1",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
