# Generated by Django 4.2.7 on 2023-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_auth1_final_otp_alter_auth1_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth1",
            name="final_otp",
            field=models.IntegerField(null=True),
        ),
    ]
